-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRnzNpNdxbYxvpGxv
AUe2mZFmoUaA6myZEhLpb/dfjSWgCgYIKoZIzj0DAQehRANCAASn0WvZQuCUlgZi
rMvuntDPfKdbJYMIPHXQJMIPSJuxgKhgSFEf+4ipLJnEKiRY24Fbc9Rx1wHWNps4
F8LwWzaN
-----END PRIVATE KEY-----