// Qizlar Academy ilovasi uchun barcha tashqi dependency larning re-exporti.
// Ilovada faqat shu paket ko'rinadi; asl paketlar shu yerda.
export 'package:flutter/material.dart';
export 'package:cupertino_icons/cupertino_icons.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:firebase_remote_config/firebase_remote_config.dart';
export 'package:firebase_crashlytics/firebase_crashlytics.dart';
export 'package:go_router/go_router.dart';
export 'package:flutter_bloc/flutter_bloc.dart';
export 'package:get_it/get_it.dart';
export 'package:shared_preferences/shared_preferences.dart';
export 'package:equatable/equatable.dart';
export 'package:dio/dio.dart';
export 'package:flutter_staggered_animations/flutter_staggered_animations.dart';
export 'package:gaimon/gaimon.dart';
export 'package:cached_network_image/cached_network_image.dart';
export 'package:lucide_icons_flutter/lucide_icons.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:logger/logger.dart';
export 'package:liquid_glass_renderer/liquid_glass_renderer.dart';
export 'package:liquid_glass_widgets/liquid_glass_widgets.dart';
export 'package:motor/motor.dart';
export 'package:bounce/bounce.dart';
export 'package:skeletonizer/skeletonizer.dart';
export 'package:octo_image/octo_image.dart';
export 'package:flutter_theme_circle_animation/flutter_theme_circle_animation.dart';
export 'package:delightful_toast/delight_toast.dart';
export 'package:lottie_tgs/lottie.dart';
export 'package:omni_video_player/omni_video_player.dart';
export 'package:pinput/pinput.dart';
export 'package:google_sign_in/google_sign_in.dart';
export 'package:flutter_html/flutter_html.dart' hide Marker, Normalize;
export 'package:image_picker/image_picker.dart';
export 'package:adaptive_media_picker/adaptive_media_picker.dart' hide ImageSource;
export 'package:permission_handler/permission_handler.dart';
export 'package:url_launcher/url_launcher.dart';
export 'package:share_plus/share_plus.dart';
export 'package:pdfrx/pdfrx.dart';
