-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPLJ42dnDRFb517dR
wR0vHNTANlHtVe7i7x8KoydoJpSgCgYIKoZIzj0DAQehRANCAASayaJaebBIUJCG
xjQ36CZ4Fy+BSA0wbua2h1EJQrzV9MAeGcwiQN2ztuduuorCqzgGNptAPOlpiEEI
VDleNQRc
-----END PRIVATE KEY-----